version: "3"
services:
    db1:
        image: "postgres:11"
        container_name: "my_postgres1"
        networks:
            - my_network
        ports:
            - "54320:5432"
        volumes:
            - my_dbdata1:/var/lib/postgresql/data
            - ${HOME}/tpch-kit/:/var/lib/postgresql/tpch
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=root
    db2:
        image: "postgres:11"
        container_name: "my_postgres2"
        networks:
            - my_network
        ports:
            - "5433:5432"
        volumes:
            - my_dbdata2:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=root

    airflow:
        image: puckel/docker-airflow
        container_name: "airflow"
        networks:
            - my_network
        ports:
            - "8080:8080"
        environment:
            - PYTHONPATH=/usr/local/airflow/operators/
        volumes:
            - my_dbdata1:/usr/local/airflow/data1
            - my_dbdata2:/usr/local/airflow/data2
            - ${HOME}/dags/:/usr/local/airflow/dags
            - ${HOME}/dags/operators/:/usr/local/airflow/operators/
        command: webserver

networks:
    my_network:
        driver: bridge

volumes:
    my_dbdata1:
    my_dbdata2:
